### ISSUE TITLE
Banners Should Support Videos

### ISSUE THREAD

**Issue by jonfroehlich** [makeabilitylab/makeabilitylabwebsite#282]
Banners on pages should support auto-playing videos (like the [Project Sidewalk](http://projectsidewalk.io/) webpage). Videos will obviously have to be carefully selected for this.

**Comment by SeokbinKang** [comment]
This seems to require modifications to the Banner model. Should we exclude this from Hackerthon Task?

**Comment by jonfroehlich** [comment]
Good point. Yes. Tag removed.

**Comment by jonfroehlich** [comment]
Here's a test video we can try: https://www.dropbox.com/scl/fi/jgz279kqv4cbm59fpi1mi/SoundWatch_720p.mp4?rlkey=ddr30zn6tazytx19ly9w2zcwv&dl=0

**Comment by jonfroehlich** [comment]
From Bing Chat:

To serve a video as a background in an HTML banner, you can use the HTML5 `<video>` tag. Here's a simple example:

```html
<div class="banner">
    <video autoplay loop muted playsinline>
        <source src="path_to_your_video.mp4" type="video/mp4">
    </video>
</div>
```

In the CSS, you can make the video fill the banner like this:

```css
.banner {
    position: relative;
    overflow: hidden;
    width: 100%;
    height: 500px; /* Adjust as needed */
}

.banner video {
    position: absolute;
    top: 50%;
    left: 50%;
    min-width: 100%;
    min-height: 100%;
    width: auto;
    height: auto;
    z-index: -1;
    transform: translate(-50%, -50%);
}
```

This will ensure that the video always covers the entire banner, regardless of its aspect ratio.

To optimize the video for web use, you can consider the following:

1. **Video Format**: Use MP4 format as it is widely supported and offers good quality for smaller file sizes.
2. **Video Length**: Keep your video short. A shorter video means a smaller file size.
3. **Video Quality**: You don't need a high-resolution video for a background. Reducing the quality will significantly decrease the file size.
4. **Video Bitrate**: Lowering the bitrate reduces the file size but also reduces video quality. Find a balance that maintains an acceptable quality.
5. **Use a Video Converter**: There are many online tools and software that can help you optimize your videos for web use.

Remember to include a fallback image for browsers that do not support the `<video>` tag:

```html
<div class="banner">
    <video autoplay loop muted playsinline poster="fallback.jpg">
        <source src="path_to_your_video.mp4" type="video/mp4">
    </video>
</div>
```

In this case, `fallback.jpg` will be displayed if the video cannot be loaded. The `poster` attribute specifies an image to be shown while the video is downloading, or until the user hits the play button.

Please note that autoplaying videos might not work on some mobile devices due to data-saving features. Always test on multiple devices and browsers to ensure compatibility.
